import type { Evidence, QuestDraft, SkillNode } from "@/lib/domain";

export const supportedLocales = ["fr", "en", "de", "es"] as const;
export type Locale = (typeof supportedLocales)[number];
export const defaultLocale: Locale = "fr";

export function isLocale(value: string | undefined | null): value is Locale {
  return supportedLocales.includes(value as Locale);
}

const dictionaries = {
  fr: {
    languageName: "Français",
    common: { language: "Langue", home: "Accueil ProofQuest", analyzeAnother: "Analyser un autre dépôt", openGithub: "Ouvrir sur GitHub ↗", close: "Fermer", level: "Niv.", locked: "VERROUILLÉ", detected: "DÉTECTÉ", evidence: "Preuves", noEvidence: "Aucune preuve vérifiable détectée pour cette compétence.", objectives: "objectifs", rescan: "Réanalyser maintenant", completed: "VALIDÉ", pending: "À FAIRE" },
    home: {
      status: "PROTOTYPE / 0.4", eyebrow: "SYSTÈME DE PROGRESSION POUR DÉVELOPPEURS", title1: "Transformez votre code", title2: "en preuves.",
      intro: "ProofQuest transforme les signaux réels de vos dépôts en graphe de compétences vivant, en preuves inspectables et en quêtes techniques adaptées à ce qu'il faut apprendre ensuite.",
      analyze: "Analyser mon GitHub", demo: "Voir le profil démo", readonly: "LECTURE SEULE PAR CONCEPTION", evidenceFirst: "LES PREUVES D'ABORD", noMagic: "PAS DE SCORE MAGIQUE",
      features: [
        ["Cartographier les preuves", "Détecter des signaux explicites dans le dépôt au lieu de deviner depuis une bio."],
        ["Explorer le graphe", "Visualiser les compétences comme une constellation reliée à des preuves techniques concrètes."],
        ["Débloquer la suite", "Transformer les lacunes en quêtes ciblées avec des critères de validation clairs."],
      ],
    },
    analyze: {
      status: "ANALYSEUR DE DÉPÔT PUBLIC / 0.4", eyebrow: "PREMIER MOTEUR DE PREUVES RÉEL", title: "Donnez un dépôt à ProofQuest.",
      intro: "Le moteur lit un dépôt GitHub public en lecture seule, cartographie son arborescence et ses dépendances, puis transforme des signaux explicites en une première constellation de compétences.",
      label: "DÉPÔT GITHUB PUBLIC", placeholder: "propriétaire/dépôt ou https://github.com/propriétaire/dépôt", submit: "Analyser le dépôt",
      invalid: "Saisir un dépôt public au format propriétaire/dépôt ou une URL github.com.", foot: ["v0.4 inspecte maintenant les configurations et workflows en profondeur", "dépôts publics uniquement", "API GitHub en lecture seule"],
      noteTitle: "Ce que cette version peut réellement prouver", note1: "TypeScript strict et options de sûreté, scripts de tests/typecheck, exécution dans GitHub Actions, React/Next.js, Docker approfondi et manifests Kubernetes ciblés.",
      note2: "Elle ne juge pas encore la qualité du code, la séniorité ou la capacité globale du développeur. Ces affirmations demanderaient un modèle de preuves bien plus solide.", demo: "Ou ouvrir la démo fictive",
      failedStatus: "ÉCHEC DE L'ANALYSE", failedTitle: "Impossible de cartographier ce dépôt.", tryAnother: "Essayer un autre dépôt",
      errors: { invalid: "Le nom du propriétaire ou du dépôt GitHub est invalide.", notFound: "Dépôt introuvable ou non accessible publiquement.", rateLimit: "GitHub a refusé la requête. La limite de l'API non authentifiée est peut-être atteinte ; ajouter éventuellement GITHUB_TOKEN dans .env.local puis réessayer.", generic: "L'analyse du dépôt a échoué de façon inattendue." },
    },
    scan: {
      live: "ANALYSE EN DIRECT", eyebrow: "VRAI DÉPÔT PUBLIC", mapping: "Cartographie de {repo}.", intro: "ProofQuest convertit la structure du dépôt en preuves techniques explicites. Aucune IA n'invente les compétences pendant cette passe.", found: "TROUVÉ", wait: "ATTENTE",
      events: ["métadonnées du dépôt cartographiées", "surface des langages mesurée", "manifestes de dépendances inspectés", "signaux qualité indexés", "graphe de preuves assemblé"],
    },
    dashboard: {
      live: "PREUVES RÉELLES DU DÉPÔT", analyzedRepo: "DÉPÔT ANALYSÉ", noDescription: "Aucune description fournie pour ce dépôt.", stars: "étoiles", forks: "forks", files: "fichiers cartographiés",
      warning: "GitHub a renvoyé une arborescence tronquée. Les preuves ci-dessous sont donc partielles.", build: "BUILD DU DÉPÔT", multiLanguage: "MULTI-LANGAGE", footerEngine: "moteur de preuves ProofQuest", buildLevel: "NIVEAU DU BUILD", languageMap: "CARTE DES LANGAGES",
      constellation: "CONSTELLATION DE COMPÉTENCES", evidenceMap: "Carte des preuves détectées", detected: "DÉTECTÉES", primary: "principal", graphDetected: "détecté", noEvidenceYet: "aucune preuve pour l'instant",
      nextQuest: "PROCHAINE QUÊTE / BROUILLON", verifiable: "SIGNAUX VÉRIFIABLES", evidence: "Preuves", emptyEvidence: "Aucun signal pris en charge n'a été détecté dans cette passe.", analyzed: "Analysé en UTC", deepScan: "ANALYSE PROFONDE", historyTitle: "ÉVOLUTION ENTRE LES SCANS", historyEmpty: "Modifiez le dépôt puis relancez une analyse pour mesurer les changements réels.", historyNoChange: "Aucun changement de preuve détecté depuis le scan précédent.", historyEvidence: "preuves", historyLevel: "niveau du build", historyPrevious: "scan précédent", historyQuest: "QUÊTE VALIDÉE PAR LES PREUVES",
      metrics: { "Type safety": "Sûreté des types", "UI framework": "Framework UI", Database: "Base de données", Delivery: "Livraison", Testing: "Tests", Backend: "Backend", Frontend: "Frontend", DevOps: "DevOps" },
    },
    skill: {
      detail: "DÉTAIL DE LA COMPÉTENCE", evidenceScore: "SCORE DE PREUVES", strength: "FORCE DES PREUVES DU DÉPÔT", why: "POURQUOI PROOFQUEST L'A DÉTECTÉE", next: "PROCHAIN PALIER", linkedQuest: "QUÊTE ASSOCIÉE",
      strengths: { none: "Aucune", low: "Faible", medium: "Modérée", high: "Élevée", veryHigh: "Très élevée" },
      milestones: { locked: "Ajouter au moins un signal vérifiable lié à cette technologie.", low: "Ajouter une deuxième preuve indépendante : configuration, dépendance, tests ou fichiers dédiés.", medium: "Renforcer la preuve avec un signal qualité supplémentaire, idéalement automatisé dans la CI.", high: "Conserver ces signaux et ajouter des preuves de qualité plus profondes avant d'augmenter le niveau de confiance.", veryHigh: "Le dépôt contient déjà de nombreux signaux. Le prochain objectif sera d'évaluer leur qualité plutôt que leur simple présence." },
      names: { typescript: "TypeScript", next: "Next.js", react: "React", postgres: "PostgreSQL", testing: "Tests", cicd: "CI/CD", docker: "Docker", documentation: "Dokumentation", security: "Sicherheit", kubernetes: "Kubernetes" },
    },
    demo: { data: "DONNÉES DÉMO", exit: "Quitter le build", buildId: "BUILD ID / A17", role: "EXPLORATEUR FULL-STACK", constellation: "CONSTELLATION DE COMPÉTENCES", map: "Carte des preuves", nodes: "7 NŒUDS", currentQuest: "QUÊTE EN COURS", latest: "DERNIÈRES PREUVES", signals: "Signaux", questTitle: "Initiation aux tests", questDescription: "Ajouter une couche de tests automatisés pertinente au projet et l'exécuter dans la CI.", objective: "1 / 3 objectifs", evidence: ["Mode strict TypeScript détecté", "Workflow GitHub Actions trouvé", "12 fichiers de test/spec cartographiés", "Build Docker multi-stage détecté"] },
  },
  en: {
    languageName: "English",
    common: { language: "Language", home: "ProofQuest home", analyzeAnother: "Analyze another", openGithub: "Open on GitHub ↗", close: "Close", level: "LV.", locked: "LOCKED", detected: "DETECTED", evidence: "Evidence", noEvidence: "No verifiable evidence detected for this skill.", objectives: "objectives", rescan: "Rescan now", completed: "DONE", pending: "TODO" },
    home: { status: "PROTOTYPE / 0.4", eyebrow: "DEVELOPER PROGRESSION SYSTEM", title1: "Turn your code", title2: "into proof.", intro: "ProofQuest maps real repository signals into a living skill graph, evidence you can inspect, and technical quests built around what to learn next.", analyze: "Analyze my GitHub", demo: "View demo profile", readonly: "READ-ONLY BY DESIGN", evidenceFirst: "EVIDENCE FIRST", noMagic: "NO MAGIC SCORE", features: [["Map evidence", "Detect explicit signals from the repository instead of guessing from a bio."], ["See the graph", "Explore skills as a constellation connected to concrete technical evidence."], ["Unlock next", "Turn gaps into focused quests with clear validation criteria."]] },
    analyze: { status: "PUBLIC REPO ANALYZER / 0.4", eyebrow: "FIRST REAL EVIDENCE ENGINE", title: "Give ProofQuest a repository.", intro: "The engine reads a public GitHub repository in read-only mode, maps its file tree and dependency manifests, then turns explicit signals into a first skill constellation.", label: "PUBLIC GITHUB REPOSITORY", placeholder: "owner/repository or https://github.com/owner/repository", submit: "Scan repository", invalid: "Enter a public repository as owner/repo or a github.com URL.", foot: ["v0.4 now inspects configs and workflows deeply", "public repositories only", "read-only GitHub API"], noteTitle: "What this version can actually prove", note1: "TypeScript strictness and safety flags, test/typecheck scripts, real GitHub Actions execution, React/Next.js, deeper Docker signals and targeted Kubernetes manifests.", note2: "It does not judge code quality, seniority or developer ability yet. Those claims would require a much stronger evidence model.", demo: "Or open the fictional design demo", failedStatus: "ANALYSIS FAILED", failedTitle: "Could not map this repository.", tryAnother: "Try another repository", errors: { invalid: "Invalid GitHub owner or repository name.", notFound: "Repository not found or not publicly accessible.", rateLimit: "GitHub refused the request. The unauthenticated API rate limit may have been reached; optionally add GITHUB_TOKEN in .env.local and retry.", generic: "The repository analysis failed unexpectedly." } },
    scan: { live: "LIVE SCAN", eyebrow: "REAL PUBLIC REPOSITORY", mapping: "Mapping {repo}.", intro: "ProofQuest is converting repository structure into explicit technical evidence. No AI is inventing the skill claims in this pass.", found: "FOUND", wait: "WAIT", events: ["repository metadata mapped", "language surface measured", "dependency manifests inspected", "quality signals indexed", "skill evidence graph assembled"] },
    dashboard: { live: "LIVE REPOSITORY EVIDENCE", analyzedRepo: "ANALYZED REPOSITORY", noDescription: "No repository description provided.", stars: "stars", forks: "forks", files: "files mapped", warning: "GitHub returned a truncated repository tree. The evidence below is partial.", build: "REPOSITORY BUILD", multiLanguage: "MULTI-LANGUAGE", footerEngine: "ProofQuest evidence engine", buildLevel: "BUILD LEVEL", languageMap: "LANGUAGE MAP", constellation: "SKILL CONSTELLATION", evidenceMap: "Detected evidence map", detected: "DETECTED", primary: "primary", graphDetected: "detected", noEvidenceYet: "no evidence yet", nextQuest: "NEXT QUEST / DRAFT", verifiable: "VERIFIABLE SIGNALS", evidence: "Evidence", emptyEvidence: "No supported evidence signal was detected in this pass.", analyzed: "Analyzed at UTC", deepScan: "DEEP ANALYSIS", historyTitle: "CHANGE BETWEEN SCANS", historyEmpty: "Change the repository, then rescan it to measure real progress.", historyNoChange: "No evidence change detected since the previous scan.", historyEvidence: "evidence", historyLevel: "build level", historyPrevious: "previous scan", historyQuest: "QUEST VALIDATED BY EVIDENCE", metrics: { "Type safety": "Type safety", "UI framework": "UI framework", Database: "Database", Delivery: "Delivery", Testing: "Testing", Backend: "Backend", Frontend: "Frontend", DevOps: "DevOps" } },
    skill: { detail: "SKILL DETAIL", evidenceScore: "EVIDENCE SCORE", strength: "REPOSITORY EVIDENCE STRENGTH", why: "WHY PROOFQUEST DETECTED IT", next: "NEXT MILESTONE", linkedQuest: "LINKED QUEST", strengths: { none: "None", low: "Low", medium: "Moderate", high: "High", veryHigh: "Very high" }, milestones: { locked: "Add at least one verifiable signal related to this technology.", low: "Add a second independent proof: configuration, dependency, tests or dedicated files.", medium: "Strengthen the evidence with another quality signal, ideally automated in CI.", high: "Keep these signals and add deeper quality evidence before raising confidence further.", veryHigh: "The repository already contains many signals. The next goal is to evaluate their quality rather than mere presence." }, names: { typescript: "TypeScript", next: "Next.js", react: "React", postgres: "PostgreSQL", testing: "Testing", cicd: "CI/CD", docker: "Docker", documentation: "Documentation", security: "Security", kubernetes: "Kubernetes" } },
    demo: { data: "DEMO DATA", exit: "Exit build", buildId: "BUILD ID / A17", role: "FULL-STACK EXPLORER", constellation: "SKILL CONSTELLATION", map: "Evidence map", nodes: "7 NODES", currentQuest: "CURRENT QUEST", latest: "LATEST EVIDENCE", signals: "Signals", questTitle: "Testing Initiate", questDescription: "Add a meaningful automated test layer to the project and run it in CI.", objective: "1 / 3 objectives", evidence: ["TypeScript strict mode detected", "GitHub Actions workflow found", "12 test/spec files mapped", "Docker multi-stage build detected"] },
  },
  de: {
    languageName: "Deutsch",
    common: { language: "Sprache", home: "ProofQuest Startseite", analyzeAnother: "Anderes Repository analysieren", openGithub: "Auf GitHub öffnen ↗", close: "Schließen", level: "ST.", locked: "GESPERRT", detected: "ERKANNT", evidence: "Nachweise", noEvidence: "Für diese Fähigkeit wurden keine überprüfbaren Nachweise erkannt.", objectives: "Ziele", rescan: "Jetzt neu analysieren", completed: "ERLEDIGT", pending: "OFFEN" },
    home: { status: "PROTOTYP / 0.4", eyebrow: "FORTSCHRITTSSYSTEM FÜR ENTWICKLER", title1: "Code in echte", title2: "Nachweise verwandeln.", intro: "ProofQuest verwandelt reale Repository-Signale in einen lebendigen Skill-Graphen, überprüfbare Nachweise und technische Quests für den nächsten Lernschritt.", analyze: "Mein GitHub analysieren", demo: "Demo-Profil ansehen", readonly: "NUR LESEN", evidenceFirst: "NACHWEISE ZUERST", noMagic: "KEIN MAGISCHER SCORE", features: [["Nachweise abbilden", "Explizite Repository-Signale erkennen, statt aus einer Bio zu raten."], ["Graph erkunden", "Fähigkeiten als Konstellation mit konkreten technischen Nachweisen anzeigen."], ["Nächstes freischalten", "Lücken in fokussierte Quests mit klaren Prüfkriterien verwandeln."]] },
    analyze: { status: "ÖFFENTLICHER REPO-ANALYSATOR / 0.4", eyebrow: "ERSTE ECHTE EVIDENZ-ENGINE", title: "Geben Sie ProofQuest ein Repository.", intro: "Die Engine liest ein öffentliches GitHub-Repository schreibgeschützt, kartiert Dateibaum und Abhängigkeiten und erzeugt daraus eine erste Skill-Konstellation.", label: "ÖFFENTLICHES GITHUB-REPOSITORY", placeholder: "owner/repository oder https://github.com/owner/repository", submit: "Repository scannen", invalid: "Ein öffentliches Repository als owner/repo oder github.com-URL eingeben.", foot: ["v0.4 fokussiert JS/TS-Nachweise", "nur öffentliche Repositories", "GitHub-API nur lesend"], noteTitle: "Was diese Version wirklich nachweisen kann", note1: "TypeScript, React, Next.js, grundlegende PostgreSQL-Signale, Tests, GitHub Actions, Docker sowie Kubernetes/Helm-Dateien.", note2: "Codequalität, Seniorität oder allgemeine Entwicklerfähigkeit werden noch nicht bewertet. Dafür wäre ein deutlich stärkeres Evidenzmodell nötig.", demo: "Oder die fiktive Design-Demo öffnen", failedStatus: "ANALYSE FEHLGESCHLAGEN", failedTitle: "Dieses Repository konnte nicht kartiert werden.", tryAnother: "Anderes Repository versuchen", errors: { invalid: "Ungültiger GitHub-Besitzer- oder Repository-Name.", notFound: "Repository nicht gefunden oder nicht öffentlich zugänglich.", rateLimit: "GitHub hat die Anfrage abgelehnt. Möglicherweise ist das unauthentifizierte API-Limit erreicht; optional GITHUB_TOKEN in .env.local hinzufügen und erneut versuchen.", generic: "Die Repository-Analyse ist unerwartet fehlgeschlagen." } },
    scan: { live: "LIVE-SCAN", eyebrow: "ECHTES ÖFFENTLICHES REPOSITORY", mapping: "Kartiere {repo}.", intro: "ProofQuest wandelt die Repository-Struktur in explizite technische Nachweise um. In diesem Durchlauf erfindet keine KI Skill-Aussagen.", found: "GEFUNDEN", wait: "WARTEN", events: ["Repository-Metadaten kartiert", "Sprachanteile gemessen", "Abhängigkeits-Manifeste geprüft", "Qualitätssignale indexiert", "Evidenzgraph aufgebaut"] },
    dashboard: { live: "LIVE-REPOSITORY-NACHWEISE", analyzedRepo: "ANALYSIERTES REPOSITORY", noDescription: "Keine Repository-Beschreibung vorhanden.", stars: "Sterne", forks: "Forks", files: "Dateien kartiert", warning: "GitHub hat einen gekürzten Repository-Baum geliefert. Die Nachweise sind daher unvollständig.", build: "REPOSITORY-BUILD", multiLanguage: "MEHRSPRACHIG", footerEngine: "ProofQuest Evidenz-Engine", buildLevel: "BUILD-STUFE", languageMap: "SPRACHENKARTE", constellation: "SKILL-KONSTELLATION", evidenceMap: "Erkannte Evidenzkarte", detected: "ERKANNT", primary: "primär", graphDetected: "erkannt", noEvidenceYet: "noch kein Nachweis", nextQuest: "NÄCHSTE QUEST / ENTWURF", verifiable: "ÜBERPRÜFBARE SIGNALE", evidence: "Nachweise", emptyEvidence: "In diesem Durchlauf wurde kein unterstütztes Evidenzsignal erkannt.", analyzed: "Analysiert um UTC", deepScan: "TIEFENANALYSE", historyTitle: "ÄNDERUNG ZWISCHEN SCANS", historyEmpty: "Repository ändern und erneut analysieren, um echte Fortschritte zu messen.", historyNoChange: "Seit dem vorherigen Scan wurde keine Evidenzänderung erkannt.", historyEvidence: "Nachweise", historyLevel: "Build-Stufe", historyPrevious: "vorheriger Scan", historyQuest: "QUEST DURCH NACHWEISE BESTÄTIGT", metrics: { "Type safety": "Typsicherheit", "UI framework": "UI-Framework", Database: "Datenbank", Delivery: "Auslieferung", Testing: "Tests", Backend: "Backend", Frontend: "Frontend", DevOps: "DevOps" } },
    skill: { detail: "SKILL-DETAIL", evidenceScore: "EVIDENZ-SCORE", strength: "STÄRKE DER REPOSITORY-NACHWEISE", why: "WARUM PROOFQUEST DIES ERKANNT HAT", next: "NÄCHSTER MEILENSTEIN", linkedQuest: "VERKNÜPFTE QUEST", strengths: { none: "Keine", low: "Niedrig", medium: "Mittel", high: "Hoch", veryHigh: "Sehr hoch" }, milestones: { locked: "Mindestens ein überprüfbares Signal zu dieser Technologie hinzufügen.", low: "Einen zweiten unabhängigen Nachweis hinzufügen: Konfiguration, Abhängigkeit, Tests oder eigene Dateien.", medium: "Die Evidenz mit einem weiteren Qualitätssignal stärken, idealerweise automatisiert in CI.", high: "Diese Signale beibehalten und tiefere Qualitätsnachweise ergänzen.", veryHigh: "Das Repository enthält bereits viele Signale. Als Nächstes sollte ihre Qualität statt nur ihrer Existenz bewertet werden." }, names: { typescript: "TypeScript", next: "Next.js", react: "React", postgres: "PostgreSQL", testing: "Tests", cicd: "CI/CD", docker: "Docker", documentation: "Documentation", security: "Sécurité", kubernetes: "Kubernetes" } },
    demo: { data: "DEMO-DATEN", exit: "Build verlassen", buildId: "BUILD ID / A17", role: "FULL-STACK-ENTDECKER", constellation: "SKILL-KONSTELLATION", map: "Evidenzkarte", nodes: "7 KNOTEN", currentQuest: "AKTUELLE QUEST", latest: "NEUESTE NACHWEISE", signals: "Signale", questTitle: "Test-Einstieg", questDescription: "Eine sinnvolle automatisierte Testschicht hinzufügen und in CI ausführen.", objective: "1 / 3 Ziele", evidence: ["TypeScript-Strict-Mode erkannt", "GitHub-Actions-Workflow gefunden", "12 Test/Spec-Dateien kartiert", "Docker-Multi-Stage-Build erkannt"] },
  },
  es: {
    languageName: "Español",
    common: { language: "Idioma", home: "Inicio de ProofQuest", analyzeAnother: "Analizar otro repositorio", openGithub: "Abrir en GitHub ↗", close: "Cerrar", level: "NV.", locked: "BLOQUEADO", detected: "DETECTADO", evidence: "Evidencias", noEvidence: "No se detectaron evidencias verificables para esta habilidad.", objectives: "objetivos", rescan: "Volver a analizar", completed: "HECHO", pending: "PENDIENTE" },
    home: { status: "PROTOTIPO / 0.4", eyebrow: "SISTEMA DE PROGRESIÓN PARA DESARROLLADORES", title1: "Convierte tu código", title2: "en pruebas.", intro: "ProofQuest transforma señales reales del repositorio en un grafo vivo de habilidades, evidencias inspeccionables y misiones técnicas basadas en lo que conviene aprender después.", analyze: "Analizar mi GitHub", demo: "Ver perfil demo", readonly: "SOLO LECTURA POR DISEÑO", evidenceFirst: "PRIMERO LAS EVIDENCIAS", noMagic: "SIN PUNTUACIÓN MÁGICA", features: [["Mapear evidencias", "Detectar señales explícitas del repositorio en vez de adivinar a partir de una bio."], ["Ver el grafo", "Explorar habilidades como una constelación conectada a evidencias técnicas concretas."], ["Desbloquear lo siguiente", "Convertir carencias en misiones enfocadas con criterios de validación claros."]] },
    analyze: { status: "ANALIZADOR DE REPO PÚBLICO / 0.4", eyebrow: "PRIMER MOTOR DE EVIDENCIAS REAL", title: "Dale un repositorio a ProofQuest.", intro: "El motor lee un repositorio público de GitHub en modo solo lectura, mapea su árbol de archivos y dependencias y convierte señales explícitas en una primera constelación de habilidades.", label: "REPOSITORIO PÚBLICO DE GITHUB", placeholder: "propietario/repositorio o https://github.com/propietario/repositorio", submit: "Escanear repositorio", invalid: "Introducir un repositorio público como propietario/repo o una URL de github.com.", foot: ["v0.4 ahora inspecciona configuraciones y workflows en profundidad", "solo repositorios públicos", "API de GitHub en solo lectura"], noteTitle: "Lo que esta versión puede demostrar de verdad", note1: "Strictness y opciones de seguridad de TypeScript, scripts de test/typecheck, ejecución real en GitHub Actions, React/Next.js, señales Docker profundas y manifiestos Kubernetes específicos.", note2: "Todavía no juzga la calidad del código, la seniority ni la capacidad global del desarrollador. Esas afirmaciones requieren un modelo de evidencias mucho más sólido.", demo: "O abrir la demo ficticia", failedStatus: "ANÁLISIS FALLIDO", failedTitle: "No se pudo mapear este repositorio.", tryAnother: "Probar otro repositorio", errors: { invalid: "Nombre de propietario o repositorio de GitHub inválido.", notFound: "Repositorio no encontrado o no accesible públicamente.", rateLimit: "GitHub rechazó la solicitud. Puede haberse alcanzado el límite de la API sin autenticar; añadir opcionalmente GITHUB_TOKEN en .env.local y volver a intentar.", generic: "El análisis del repositorio falló de forma inesperada." } },
    scan: { live: "ESCANEO EN DIRECTO", eyebrow: "REPOSITORIO PÚBLICO REAL", mapping: "Mapeando {repo}.", intro: "ProofQuest convierte la estructura del repositorio en evidencias técnicas explícitas. Ninguna IA inventa las afirmaciones de habilidades en esta pasada.", found: "ENCONTRADO", wait: "ESPERA", events: ["metadatos del repositorio mapeados", "superficie de lenguajes medida", "manifiestos de dependencias inspeccionados", "señales de calidad indexadas", "grafo de evidencias ensamblado"] },
    dashboard: { live: "EVIDENCIAS REALES DEL REPOSITORIO", analyzedRepo: "REPOSITORIO ANALIZADO", noDescription: "No se proporcionó descripción del repositorio.", stars: "estrellas", forks: "forks", files: "archivos mapeados", warning: "GitHub devolvió un árbol de repositorio truncado. Las evidencias siguientes son parciales.", build: "BUILD DEL REPOSITORIO", multiLanguage: "MULTILENGUAJE", footerEngine: "motor de evidencias ProofQuest", buildLevel: "NIVEL DEL BUILD", languageMap: "MAPA DE LENGUAJES", constellation: "CONSTELACIÓN DE HABILIDADES", evidenceMap: "Mapa de evidencias detectadas", detected: "DETECTADAS", primary: "principal", graphDetected: "detectado", noEvidenceYet: "sin evidencia aún", nextQuest: "SIGUIENTE MISIÓN / BORRADOR", verifiable: "SEÑALES VERIFICABLES", evidence: "Evidencias", emptyEvidence: "No se detectó ninguna señal compatible en esta pasada.", analyzed: "Analizado en UTC", deepScan: "ANÁLISIS PROFUNDO", historyTitle: "CAMBIO ENTRE ESCANEOS", historyEmpty: "Modifica el repositorio y vuelve a analizarlo para medir el progreso real.", historyNoChange: "No se detectaron cambios de evidencia desde el escaneo anterior.", historyEvidence: "evidencias", historyLevel: "nivel del build", historyPrevious: "escaneo anterior", historyQuest: "MISIÓN VALIDADA POR EVIDENCIAS", metrics: { "Type safety": "Seguridad de tipos", "UI framework": "Framework UI", Database: "Base de datos", Delivery: "Entrega", Testing: "Testing", Backend: "Backend", Frontend: "Frontend", DevOps: "DevOps" } },
    skill: { detail: "DETALLE DE HABILIDAD", evidenceScore: "PUNTUACIÓN DE EVIDENCIAS", strength: "FUERZA DE LAS EVIDENCIAS DEL REPOSITORIO", why: "POR QUÉ PROOFQUEST LA DETECTÓ", next: "SIGUIENTE HITO", linkedQuest: "MISIÓN ASOCIADA", strengths: { none: "Ninguna", low: "Baja", medium: "Moderada", high: "Alta", veryHigh: "Muy alta" }, milestones: { locked: "Añadir al menos una señal verificable relacionada con esta tecnología.", low: "Añadir una segunda prueba independiente: configuración, dependencia, tests o archivos dedicados.", medium: "Reforzar la evidencia con otra señal de calidad, idealmente automatizada en CI.", high: "Mantener estas señales y añadir evidencias de calidad más profundas.", veryHigh: "El repositorio ya contiene muchas señales. El siguiente objetivo será evaluar su calidad y no solo su presencia." }, names: { typescript: "TypeScript", next: "Next.js", react: "React", postgres: "PostgreSQL", testing: "Testing", cicd: "CI/CD", docker: "Docker", documentation: "Documentación", security: "Seguridad", kubernetes: "Kubernetes" } },
    demo: { data: "DATOS DEMO", exit: "Salir del build", buildId: "BUILD ID / A17", role: "EXPLORADOR FULL-STACK", constellation: "CONSTELACIÓN DE HABILIDADES", map: "Mapa de evidencias", nodes: "7 NODOS", currentQuest: "MISIÓN ACTUAL", latest: "ÚLTIMAS EVIDENCIAS", signals: "Señales", questTitle: "Iniciación al testing", questDescription: "Añadir una capa de tests automatizados útil al proyecto y ejecutarla en CI.", objective: "1 / 3 objetivos", evidence: ["Modo estricto de TypeScript detectado", "Workflow de GitHub Actions encontrado", "12 archivos test/spec mapeados", "Build Docker multi-stage detectado"] },
  },
} as const;

export type Dictionary = (typeof dictionaries)[Locale];
export function getDictionary(locale: Locale) { return dictionaries[locale]; }

export const localeLabels: Record<Locale, string> = { fr: "FR", en: "EN", de: "DE", es: "ES" };

function format(template: string, params?: Record<string, string | number>) {
  if (!params) return template;
  return Object.entries(params).reduce((value, [key, replacement]) => value.replaceAll(`{${key}}`, String(replacement)), template);
}

const evidenceMessages: Record<Locale, Record<string, string>> = {
  fr: {
    "typescript.config": "Configuration TypeScript détectée", "typescript.files": "{count} fichiers source TypeScript détectés", "typescript.dependency": "TypeScript est déclaré comme dépendance du projet",
    "typescript.strict": "Mode strict TypeScript activé", "typescript.noImplicitAny": "noImplicitAny activé", "typescript.strictNullChecks": "strictNullChecks activé", "typescript.noUncheckedIndexedAccess": "noUncheckedIndexedAccess activé", "typescript.exactOptionalPropertyTypes": "exactOptionalPropertyTypes activé", "typescript.typecheckScript": "Script de contrôle des types déclaré ({script})", "typescript.ciTypecheck": "Le contrôle des types est exécuté dans GitHub Actions", "quality.architecture": "Documentation d'architecture détectée",
    "react.dependency": "Dépendance React détectée", "react.tsx": "{count} fichiers de composants TSX détectés", "next.dependency": "Dépendance Next.js détectée", "next.config": "Configuration Next.js détectée", "next.structure": "Structure de routes Next.js détectée",
    "postgres.dependency": "Client PostgreSQL détecté ({dependency})", "postgres.prisma": "La source de données Prisma utilise PostgreSQL",
    "testing.files": "{count} fichiers de test/spec détectés", "testing.tool": "Outil de test {tool} détecté", "testing.script": "Script de test reproductible déclaré ({script})", "testing.ci": "{count} fichier(s) de workflow GitHub Actions détecté(s)", "testing.ciExec": "La suite de tests est réellement exécutée dans GitHub Actions",
    "docker.dockerfile": "Dockerfile détecté", "docker.compose": "Configuration Docker Compose détectée", "docker.multistage": "Build Docker multi-stage détecté", "docker.nonRoot": "Le conteneur passe sur un utilisateur non-root", "docker.healthcheck": "HEALTHCHECK Docker détecté", "docker.dockerignore": ".dockerignore détecté", "docker.docs": "Commande de lancement du conteneur documentée dans le README", "docker.ciBuild": "Build d'image Docker détecté dans GitHub Actions",
    "kubernetes.files": "{count} manifeste(s) Kubernetes/Helm détecté(s)", "kubernetes.deployment": "Deployment Kubernetes détecté", "kubernetes.service": "Service Kubernetes détecté", "kubernetes.probe": "Probe de santé Kubernetes détectée", "kubernetes.resources": "Configuration de ressources Kubernetes détectée", "cicd.workflow": "{count} workflow(s) GitHub Actions détecté(s)", "cicd.build": "Un build de production est exécuté dans la CI", "cicd.qualityGate": "Un contrôle de tests ou de types s’exécute dans la CI", "documentation.readme": "README racine détecté", "documentation.architecture": "Documentation d’architecture détectée", "documentation.docs": "{count} fichier(s) de documentation détecté(s)", "security.policy": "Politique SECURITY détectée", "security.dependencyBot": "Maintenance automatisée des dépendances détectée", "security.codeScanning": "Analyse de sécurité automatisée détectée dans la CI"
  },
  en: {
    "typescript.config": "TypeScript configuration detected", "typescript.files": "{count} TypeScript source files detected", "typescript.dependency": "TypeScript is declared as a project dependency",
    "typescript.strict": "TypeScript strict mode is enabled", "typescript.noImplicitAny": "noImplicitAny is enabled", "typescript.strictNullChecks": "strictNullChecks is enabled", "typescript.noUncheckedIndexedAccess": "noUncheckedIndexedAccess is enabled", "typescript.exactOptionalPropertyTypes": "exactOptionalPropertyTypes is enabled", "typescript.typecheckScript": "Repeatable type-check script declared ({script})", "typescript.ciTypecheck": "Type checking runs in GitHub Actions", "quality.architecture": "Architecture documentation detected",
    "react.dependency": "React dependency detected", "react.tsx": "{count} TSX component files detected", "next.dependency": "Next.js dependency detected", "next.config": "Next.js configuration detected", "next.structure": "Next.js route structure detected",
    "postgres.dependency": "PostgreSQL client dependency detected ({dependency})", "postgres.prisma": "Prisma datasource uses PostgreSQL",
    "testing.files": "{count} test/spec files detected", "testing.tool": "{tool} test tooling detected", "testing.script": "Repeatable test script declared ({script})", "testing.ci": "{count} GitHub Actions workflow file(s) detected", "testing.ciExec": "The test suite actually runs in GitHub Actions",
    "docker.dockerfile": "Dockerfile detected", "docker.compose": "Docker Compose configuration detected", "docker.multistage": "Multi-stage Docker build detected", "docker.nonRoot": "Container switches to a non-root user", "docker.healthcheck": "Docker HEALTHCHECK detected", "docker.dockerignore": ".dockerignore detected", "docker.docs": "Container run command documented in the README", "docker.ciBuild": "Docker image build detected in GitHub Actions",
    "kubernetes.files": "{count} Kubernetes/Helm manifest file(s) detected", "kubernetes.deployment": "Kubernetes Deployment detected", "kubernetes.service": "Kubernetes Service detected", "kubernetes.probe": "Kubernetes health probe detected", "kubernetes.resources": "Kubernetes resource configuration detected", "cicd.workflow": "{count} GitHub Actions workflow(s) detected", "cicd.build": "A production build is executed in CI", "cicd.qualityGate": "A test or type-check quality gate runs in CI", "documentation.readme": "Root README detected", "documentation.architecture": "Architecture documentation detected", "documentation.docs": "{count} documentation file(s) detected", "security.policy": "SECURITY policy detected", "security.dependencyBot": "Automated dependency maintenance detected", "security.codeScanning": "Automated security scanning detected in CI"
  },
  de: {
    "typescript.config": "TypeScript-Konfiguration erkannt", "typescript.files": "{count} TypeScript-Quelldateien erkannt", "typescript.dependency": "TypeScript ist als Projektabhängigkeit deklariert",
    "typescript.strict": "TypeScript-Strict-Modus ist aktiviert", "typescript.noImplicitAny": "noImplicitAny ist aktiviert", "typescript.strictNullChecks": "strictNullChecks ist aktiviert", "typescript.noUncheckedIndexedAccess": "noUncheckedIndexedAccess ist aktiviert", "typescript.exactOptionalPropertyTypes": "exactOptionalPropertyTypes ist aktiviert", "typescript.typecheckScript": "Wiederholbares Type-Check-Skript deklariert ({script})", "typescript.ciTypecheck": "Type-Checking läuft in GitHub Actions", "quality.architecture": "Architekturdokumentation erkannt",
    "react.dependency": "React-Abhängigkeit erkannt", "react.tsx": "{count} TSX-Komponentendateien erkannt", "next.dependency": "Next.js-Abhängigkeit erkannt", "next.config": "Next.js-Konfiguration erkannt", "next.structure": "Next.js-Routenstruktur erkannt",
    "postgres.dependency": "PostgreSQL-Client erkannt ({dependency})", "postgres.prisma": "Prisma-Datenquelle verwendet PostgreSQL",
    "testing.files": "{count} Test/Spec-Dateien erkannt", "testing.tool": "Testwerkzeug {tool} erkannt", "testing.script": "Wiederholbares Testskript deklariert ({script})", "testing.ci": "{count} GitHub-Actions-Workflow-Datei(en) erkannt", "testing.ciExec": "Die Testsuite läuft tatsächlich in GitHub Actions",
    "docker.dockerfile": "Dockerfile erkannt", "docker.compose": "Docker-Compose-Konfiguration erkannt", "docker.multistage": "Docker-Multi-Stage-Build erkannt", "docker.nonRoot": "Container wechselt zu einem Nicht-Root-Benutzer", "docker.healthcheck": "Docker HEALTHCHECK erkannt", "docker.dockerignore": ".dockerignore erkannt", "docker.docs": "Container-Startbefehl im README dokumentiert", "docker.ciBuild": "Docker-Image-Build in GitHub Actions erkannt",
    "kubernetes.files": "{count} Kubernetes/Helm-Manifest(e) erkannt", "kubernetes.deployment": "Kubernetes Deployment erkannt", "kubernetes.service": "Kubernetes Service erkannt", "kubernetes.probe": "Kubernetes Health-Probe erkannt", "kubernetes.resources": "Kubernetes-Ressourcenkonfiguration erkannt", "cicd.workflow": "{count} GitHub-Actions-Workflow(s) erkannt", "cicd.build": "Ein Produktions-Build läuft in CI", "cicd.qualityGate": "Tests oder Type-Checks laufen als Qualitäts-Gate in CI", "documentation.readme": "Root-README erkannt", "documentation.architecture": "Architekturdokumentation erkannt", "documentation.docs": "{count} Dokumentationsdatei(en) erkannt", "security.policy": "SECURITY-Richtlinie erkannt", "security.dependencyBot": "Automatisierte Abhängigkeitswartung erkannt", "security.codeScanning": "Automatisiertes Security-Scanning in CI erkannt"
  },
  es: {
    "typescript.config": "Configuración de TypeScript detectada", "typescript.files": "{count} archivos fuente TypeScript detectados", "typescript.dependency": "TypeScript está declarado como dependencia del proyecto",
    "typescript.strict": "Modo strict de TypeScript activado", "typescript.noImplicitAny": "noImplicitAny activado", "typescript.strictNullChecks": "strictNullChecks activado", "typescript.noUncheckedIndexedAccess": "noUncheckedIndexedAccess activado", "typescript.exactOptionalPropertyTypes": "exactOptionalPropertyTypes activado", "typescript.typecheckScript": "Script reproducible de comprobación de tipos declarado ({script})", "typescript.ciTypecheck": "La comprobación de tipos se ejecuta en GitHub Actions", "quality.architecture": "Documentación de arquitectura detectada",
    "react.dependency": "Dependencia de React detectada", "react.tsx": "{count} archivos de componentes TSX detectados", "next.dependency": "Dependencia de Next.js detectada", "next.config": "Configuración de Next.js detectada", "next.structure": "Estructura de rutas Next.js detectada",
    "postgres.dependency": "Cliente PostgreSQL detectado ({dependency})", "postgres.prisma": "La fuente de datos Prisma usa PostgreSQL",
    "testing.files": "{count} archivos test/spec detectados", "testing.tool": "Herramienta de testing {tool} detectada", "testing.script": "Script de test reproducible declarado ({script})", "testing.ci": "{count} archivo(s) de workflow GitHub Actions detectado(s)", "testing.ciExec": "La suite de tests se ejecuta realmente en GitHub Actions",
    "docker.dockerfile": "Dockerfile detectado", "docker.compose": "Configuración Docker Compose detectada", "docker.multistage": "Build Docker multi-stage detectado", "docker.nonRoot": "El contenedor cambia a un usuario no-root", "docker.healthcheck": "HEALTHCHECK de Docker detectado", "docker.dockerignore": ".dockerignore detectado", "docker.docs": "Comando de ejecución del contenedor documentado en el README", "docker.ciBuild": "Build de imagen Docker detectado en GitHub Actions",
    "kubernetes.files": "{count} manifiesto(s) Kubernetes/Helm detectado(s)", "kubernetes.deployment": "Deployment de Kubernetes detectado", "kubernetes.service": "Service de Kubernetes detectado", "kubernetes.probe": "Probe de salud de Kubernetes detectada", "kubernetes.resources": "Configuración de recursos de Kubernetes detectada", "cicd.workflow": "{count} workflow(s) de GitHub Actions detectado(s)", "cicd.build": "Se ejecuta un build de producción en CI", "cicd.qualityGate": "Se ejecutan tests o comprobación de tipos como control de calidad en CI", "documentation.readme": "README raíz detectado", "documentation.architecture": "Documentación de arquitectura detectada", "documentation.docs": "{count} archivo(s) de documentación detectado(s)", "security.policy": "Política SECURITY detectada", "security.dependencyBot": "Mantenimiento automático de dependencias detectado", "security.codeScanning": "Análisis de seguridad automatizado detectado en CI"
  },
};

export function evidenceLabel(item: Evidence, locale: Locale) {
  const template = item.messageKey ? evidenceMessages[locale][item.messageKey] : undefined;
  return template ? format(template, item.messageParams) : item.label;
}

const questCopies: Record<Locale, Record<string, { title: string; description: string; criteria: string[] }>> = {
  fr: { testing: { title: "Initiation aux tests", description: "Construire une vraie couche de tests automatisés et l'intégrer au workflow du dépôt.", criteria: ["Ajouter au moins 5 tests automatisés pertinents", "Ajouter une commande de test reproductible", "Exécuter la suite de tests dans la CI"] }, docker: { title: "Forge de conteneur", description: "Rendre le projet reproductible dans un environnement local conteneurisé.", criteria: ["Ajouter un Dockerfile", "Utiliser un build multi-stage", "Documenter la commande de lancement"] }, cicd: { title: "Circuit de livraison", description: "Transformer l’automatisation du dépôt en pipeline de livraison reproductible avec de vrais contrôles qualité.", criteria: ["Ajouter un workflow GitHub Actions", "Exécuter un build dans la CI", "Exécuter les tests ou le contrôle des types dans la CI"] }, documentation: { title: "Balise de connaissance", description: "Rendre le dépôt compréhensible sans dépendre de connaissances implicites.", criteria: ["Conserver un README racine", "Documenter l’architecture", "Ajouter au moins 2 fichiers de documentation"] }, security: { title: "Protocole bouclier", description: "Ajouter une responsabilité sécurité explicite, la maintenance des dépendances et une analyse automatisée.", criteria: ["Ajouter une politique SECURITY", "Activer Dependabot ou Renovate", "Activer CodeQL ou la revue des dépendances dans la CI"] }, kubernetes: { title: "Porte de l'orchestration", description: "Transformer l'application conteneurisée en workload Kubernetes minimal déployable.", criteria: ["Ajouter un manifeste Deployment", "Ajouter un manifeste Service", "Définir des probes readiness ou liveness"] }, hardening: { title: "Renforcement des preuves", description: "Augmenter la qualité des preuves du dépôt avant de débloquer un défi plus important.", criteria: ["Conserver un typage strict", "Documenter l'architecture", "Exécuter le contrôle des types dans la CI"] } },
  en: { testing: { title: "Testing Initiate", description: "Build a meaningful automated test layer and make it part of the repository workflow.", criteria: ["Add at least 5 meaningful automated tests", "Add a repeatable test command", "Run the test suite in CI"] }, docker: { title: "Container Forge", description: "Make the project reproducible in a containerized local environment.", criteria: ["Add a Dockerfile", "Use a multi-stage build", "Document the run command"] }, cicd: { title: "Delivery Circuit", description: "Turn repository automation into a repeatable delivery pipeline with real quality gates.", criteria: ["Add a GitHub Actions workflow", "Run a build in CI", "Run tests or type checking in CI"] }, documentation: { title: "Knowledge Beacon", description: "Make the repository understandable without relying on tribal knowledge.", criteria: ["Keep a root README", "Document the architecture", "Add at least 2 documentation files"] }, security: { title: "Shield Protocol", description: "Add explicit security ownership, dependency maintenance and automated code scanning.", criteria: ["Add a SECURITY policy", "Enable Dependabot or Renovate", "Enable CodeQL or dependency review in CI"] }, kubernetes: { title: "Orchestration Gate", description: "Turn the containerized app into a minimal deployable Kubernetes workload.", criteria: ["Add a Deployment manifest", "Add a Service manifest", "Define readiness or liveness probes"] }, hardening: { title: "Proof Hardening", description: "Increase the quality of the repository evidence before unlocking a larger challenge.", criteria: ["Keep strict typing enabled", "Document the architecture", "Run type checking in CI"] } },
  de: { testing: { title: "Test-Einstieg", description: "Eine sinnvolle automatisierte Testschicht aufbauen und in den Repository-Workflow integrieren.", criteria: ["Mindestens 5 sinnvolle automatisierte Tests hinzufügen", "Einen reproduzierbaren Testbefehl hinzufügen", "Die Testsuite in CI ausführen"] }, docker: { title: "Container-Schmiede", description: "Das Projekt in einer containerisierten lokalen Umgebung reproduzierbar machen.", criteria: ["Ein Dockerfile hinzufügen", "Einen Multi-Stage-Build verwenden", "Startbefehl dokumentieren"] }, cicd: { title: "Delivery-Kreislauf", description: "Repository-Automatisierung in eine reproduzierbare Delivery-Pipeline mit echten Qualitäts-Gates verwandeln.", criteria: ["GitHub-Actions-Workflow hinzufügen", "Build in CI ausführen", "Tests oder Type-Checking in CI ausführen"] }, documentation: { title: "Wissenssignal", description: "Das Repository verständlich machen, ohne implizites Teamwissen vorauszusetzen.", criteria: ["Root-README pflegen", "Architektur dokumentieren", "Mindestens 2 Dokumentationsdateien hinzufügen"] }, security: { title: "Schutzprotokoll", description: "Explizite Security-Verantwortung, Abhängigkeitswartung und automatisiertes Scanning hinzufügen.", criteria: ["SECURITY-Richtlinie hinzufügen", "Dependabot oder Renovate aktivieren", "CodeQL oder Dependency Review in CI aktivieren"] }, kubernetes: { title: "Orchestrierungs-Tor", description: "Die containerisierte App in einen minimal deploybaren Kubernetes-Workload verwandeln.", criteria: ["Deployment-Manifest hinzufügen", "Service-Manifest hinzufügen", "Readiness- oder Liveness-Probes definieren"] }, hardening: { title: "Evidenz härten", description: "Die Qualität der Repository-Nachweise erhöhen, bevor eine größere Herausforderung freigeschaltet wird.", criteria: ["Striktes Typing beibehalten", "Architektur dokumentieren", "Type-Checking in CI ausführen"] } },
  es: { testing: { title: "Iniciación al testing", description: "Construir una capa útil de tests automatizados e integrarla en el flujo del repositorio.", criteria: ["Añadir al menos 5 tests automatizados relevantes", "Añadir un comando de test reproducible", "Ejecutar la suite de tests en CI"] }, docker: { title: "Forja de contenedores", description: "Hacer el proyecto reproducible en un entorno local contenedorizado.", criteria: ["Añadir un Dockerfile", "Usar un build multi-stage", "Documentar el comando de ejecución"] }, cicd: { title: "Circuito de entrega", description: "Convertir la automatización del repositorio en un pipeline de entrega reproducible con controles de calidad reales.", criteria: ["Añadir un workflow de GitHub Actions", "Ejecutar un build en CI", "Ejecutar tests o comprobación de tipos en CI"] }, documentation: { title: "Faro de conocimiento", description: "Hacer que el repositorio sea comprensible sin depender de conocimiento implícito.", criteria: ["Mantener un README raíz", "Documentar la arquitectura", "Añadir al menos 2 archivos de documentación"] }, security: { title: "Protocolo escudo", description: "Añadir responsabilidad de seguridad, mantenimiento de dependencias y análisis automatizado.", criteria: ["Añadir una política SECURITY", "Activar Dependabot o Renovate", "Activar CodeQL o revisión de dependencias en CI"] }, kubernetes: { title: "Puerta de orquestación", description: "Convertir la app contenedorizada en un workload mínimo desplegable en Kubernetes.", criteria: ["Añadir un manifiesto Deployment", "Añadir un manifiesto Service", "Definir probes de readiness o liveness"] }, hardening: { title: "Refuerzo de evidencias", description: "Aumentar la calidad de las evidencias antes de desbloquear un reto mayor.", criteria: ["Mantener tipado strict", "Documentar la arquitectura", "Ejecutar la comprobación de tipos en CI"] } },
};

export function questCopy(quest: QuestDraft, locale: Locale) {
  return questCopies[locale][quest.kind] ?? { title: quest.title, description: quest.description, criteria: quest.criteria };
}

export function questTitleFor(kind: QuestDraft["kind"], locale: Locale) {
  return questCopies[locale][kind]?.title ?? kind;
}

export function skillName(skill: SkillNode, locale: Locale) {
  return getDictionary(locale).skill.names[skill.id as keyof (typeof dictionaries)["fr"]["skill"]["names"]] ?? skill.name;
}

export function metricLabel(label: string, locale: Locale) {
  const metrics = getDictionary(locale).dashboard.metrics as Record<string, string>;
  return metrics[label] ?? label;
}

export function evidenceStrength(progress: number, locale: Locale) {
  const s = getDictionary(locale).skill.strengths;
  if (progress <= 0) return s.none;
  if (progress < 35) return s.low;
  if (progress < 65) return s.medium;
  if (progress < 85) return s.high;
  return s.veryHigh;
}

export function milestoneFor(progress: number, state: SkillNode["state"], locale: Locale) {
  const m = getDictionary(locale).skill.milestones;
  if (state === "locked" || progress <= 0) return m.locked;
  if (progress < 35) return m.low;
  if (progress < 65) return m.medium;
  if (progress < 85) return m.high;
  return m.veryHigh;
}
