import type { Locale } from "./i18n";

const copy = {
  fr: { edit: "Éditer mon profil", headline: "Titre", bio: "Bio", links: "Liens publics HTTPS (un par ligne, 3 maximum)", save: "Enregistrer", saving: "Enregistrement…", saved: "Profil enregistré.", invalid: "Vérifiez les longueurs et les liens HTTPS, sans identifiants ni espaces.", error: "Enregistrement impossible. Réessayez.", privacy: "Ces informations apparaîtront uniquement si vous rendez votre profil public.", share: "Partager la preuve", copy: "Copier le lien", copied: "Lien copié", shared: "Partage terminé", shareError: "Copie impossible. Sélectionnez le lien ci-dessous.", publicHint: "Rendez votre profil public pour partager vos preuves.", verified: "Preuve vérifiée", portfolio: "Portfolio de preuves", unavailable: "Contenu indisponible", back: "Retour à ma progression" },
  en: { edit: "Edit my profile", headline: "Headline", bio: "Bio", links: "Public HTTPS links (one per line, up to 3)", save: "Save", saving: "Saving…", saved: "Profile saved.", invalid: "Check lengths and HTTPS links, without credentials or spaces.", error: "Could not save. Try again.", privacy: "These details appear only when you make your profile public.", share: "Share proof", copy: "Copy link", copied: "Link copied", shared: "Share completed", shareError: "Could not copy. Select the link below.", publicHint: "Make your profile public to share your proofs.", verified: "Verified proof", portfolio: "Proof portfolio", unavailable: "Content unavailable", back: "Back to my progress" },
  de: { edit: "Mein Profil bearbeiten", headline: "Titel", bio: "Biografie", links: "Öffentliche HTTPS-Links (einer pro Zeile, höchstens 3)", save: "Speichern", saving: "Wird gespeichert…", saved: "Profil gespeichert.", invalid: "Längen und HTTPS-Links prüfen, ohne Zugangsdaten oder Leerzeichen.", error: "Speichern fehlgeschlagen. Erneut versuchen.", privacy: "Diese Angaben erscheinen nur, wenn Sie Ihr Profil veröffentlichen.", share: "Nachweis teilen", copy: "Link kopieren", copied: "Link kopiert", shared: "Geteilt", shareError: "Kopieren fehlgeschlagen. Wählen Sie den Link unten aus.", publicHint: "Veröffentlichen Sie Ihr Profil, um Nachweise zu teilen.", verified: "Verifizierter Nachweis", portfolio: "Nachweisportfolio", unavailable: "Inhalt nicht verfügbar", back: "Zurück zu meinem Fortschritt" },
  es: { edit: "Editar mi perfil", headline: "Título", bio: "Biografía", links: "Enlaces HTTPS públicos (uno por línea, máximo 3)", save: "Guardar", saving: "Guardando…", saved: "Perfil guardado.", invalid: "Revise las longitudes y los enlaces HTTPS, sin credenciales ni espacios.", error: "No se pudo guardar. Inténtelo de nuevo.", privacy: "Estos datos solo aparecerán cuando haga público su perfil.", share: "Compartir prueba", copy: "Copiar enlace", copied: "Enlace copiado", shared: "Compartido", shareError: "No se pudo copiar. Seleccione el enlace de abajo.", publicHint: "Haga público su perfil para compartir sus pruebas.", verified: "Prueba verificada", portfolio: "Portfolio de pruebas", unavailable: "Contenido no disponible", back: "Volver a mi progreso" },
} as const;

export function getProductCopy(locale: Locale) { return copy[locale]; }
