import type { Locale } from "./i18n";

const copy = {
  fr: { identity: "IDENTITÉ PROOFQUEST", level: "NIVEAU", repos: "DÉPÔTS ANALYSÉS", reposBody: "Dernier scan conservé pour chaque dépôt.", evidence: "PREUVES CARTOGRAPHIÉES", evidenceBody: "Signaux techniques du dernier état de vos dépôts.", quests: "QUÊTES VÉRIFIÉES", questsBody: "Récompenses attribuées uniquement après vérification GitHub.", matrix: "CARTE GLOBALE DES COMPÉTENCES", map: "Votre carte multi-dépôts", skills: "COMPÉTENCES", repositories: "dépôts", emptySkills: "Analysez un premier dépôt connecté pour construire votre carte globale.", scans: "HISTORIQUE DES SCANS", open: "Ouvrir", emptyScans: "Aucun scan cloud enregistré." },
  en: { identity: "PROOFQUEST IDENTITY", level: "LEVEL", repos: "ANALYZED REPOSITORIES", reposBody: "Latest scan retained for each repository.", evidence: "MAPPED EVIDENCE", evidenceBody: "Technical signals from the latest state of your repositories.", quests: "VERIFIED QUESTS", questsBody: "Rewards granted only after GitHub verification.", matrix: "GLOBAL SKILL MATRIX", map: "Your multi-repository map", skills: "SKILLS", repositories: "repositories", emptySkills: "Analyze your first connected repository to build your global map.", scans: "SCAN HISTORY", open: "Open", emptyScans: "No cloud scans saved." },
  de: { identity: "PROOFQUEST-IDENTITÄT", level: "LEVEL", repos: "ANALYSIERTE REPOSITORIES", reposBody: "Der letzte Scan jedes Repositories wird gespeichert.", evidence: "KARTIERTE NACHWEISE", evidenceBody: "Technische Signale aus dem aktuellen Stand Ihrer Repositories.", quests: "VERIFIZIERTE QUESTS", questsBody: "Belohnungen werden nur nach GitHub-Verifizierung vergeben.", matrix: "GLOBALE SKILL-MATRIX", map: "Ihre repositoryübergreifende Karte", skills: "SKILLS", repositories: "Repositories", emptySkills: "Analysieren Sie Ihr erstes verbundenes Repository, um Ihre globale Karte aufzubauen.", scans: "SCAN-VERLAUF", open: "Öffnen", emptyScans: "Keine Cloud-Scans gespeichert." },
  es: { identity: "IDENTIDAD PROOFQUEST", level: "NIVEL", repos: "REPOSITORIOS ANALIZADOS", reposBody: "Se conserva el último análisis de cada repositorio.", evidence: "PRUEBAS MAPEADAS", evidenceBody: "Señales técnicas del último estado de sus repositorios.", quests: "MISIONES VERIFICADAS", questsBody: "Recompensas concedidas solo tras la verificación de GitHub.", matrix: "MATRIZ GLOBAL DE COMPETENCIAS", map: "Su mapa de múltiples repositorios", skills: "COMPETENCIAS", repositories: "repositorios", emptySkills: "Analice su primer repositorio conectado para crear su mapa global.", scans: "HISTORIAL DE ANÁLISIS", open: "Abrir", emptyScans: "No hay análisis guardados en la nube." },
} as const;

export function getProgressCopy(locale: Locale) { return copy[locale]; }
